# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

class EventType(object):
    Unknown = 0
    Actual = 1
    Revision = 2
    Estimate = 3
    Calendar = 4
    Another = 99
