# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

class EventSubType(object):
    Unknown = 0
    New = 1
    Update = 2
    Unitpaint = 3
    Delete = 4
    Another = 99
