# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HeadlineCalendarEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HeadlineCalendarEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHeadlineCalendarEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HeadlineCalendarEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HeadlineCalendarEvent
    def IdBbGlobal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HeadlineCalendarEvent
    def ParsekyableDes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HeadlineCalendarEvent
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HeadlineCalendarEvent
    def EventType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # HeadlineCalendarEvent
    def EventSubtype(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # HeadlineCalendarEvent
    def EventId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HeadlineCalendarEvent
    def ObservationPeriod(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HeadlineCalendarEvent
    def ReleaseStartDt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from BlpConn.FB.DateTime import DateTime
            obj = DateTime()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HeadlineCalendarEvent
    def ReleaseEndDt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from BlpConn.FB.DateTime import DateTime
            obj = DateTime()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HeadlineCalendarEvent
    def ReleaseStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def HeadlineCalendarEventStart(builder):
    builder.StartObject(10)

def Start(builder):
    HeadlineCalendarEventStart(builder)

def HeadlineCalendarEventAddIdBbGlobal(builder, idBbGlobal):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(idBbGlobal), 0)

def AddIdBbGlobal(builder, idBbGlobal):
    HeadlineCalendarEventAddIdBbGlobal(builder, idBbGlobal)

def HeadlineCalendarEventAddParsekyableDes(builder, parsekyableDes):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(parsekyableDes), 0)

def AddParsekyableDes(builder, parsekyableDes):
    HeadlineCalendarEventAddParsekyableDes(builder, parsekyableDes)

def HeadlineCalendarEventAddDescription(builder, description):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)

def AddDescription(builder, description):
    HeadlineCalendarEventAddDescription(builder, description)

def HeadlineCalendarEventAddEventType(builder, eventType):
    builder.PrependUint8Slot(3, eventType, 0)

def AddEventType(builder, eventType):
    HeadlineCalendarEventAddEventType(builder, eventType)

def HeadlineCalendarEventAddEventSubtype(builder, eventSubtype):
    builder.PrependUint8Slot(4, eventSubtype, 0)

def AddEventSubtype(builder, eventSubtype):
    HeadlineCalendarEventAddEventSubtype(builder, eventSubtype)

def HeadlineCalendarEventAddEventId(builder, eventId):
    builder.PrependInt32Slot(5, eventId, 0)

def AddEventId(builder, eventId):
    HeadlineCalendarEventAddEventId(builder, eventId)

def HeadlineCalendarEventAddObservationPeriod(builder, observationPeriod):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(observationPeriod), 0)

def AddObservationPeriod(builder, observationPeriod):
    HeadlineCalendarEventAddObservationPeriod(builder, observationPeriod)

def HeadlineCalendarEventAddReleaseStartDt(builder, releaseStartDt):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(releaseStartDt), 0)

def AddReleaseStartDt(builder, releaseStartDt):
    HeadlineCalendarEventAddReleaseStartDt(builder, releaseStartDt)

def HeadlineCalendarEventAddReleaseEndDt(builder, releaseEndDt):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(releaseEndDt), 0)

def AddReleaseEndDt(builder, releaseEndDt):
    HeadlineCalendarEventAddReleaseEndDt(builder, releaseEndDt)

def HeadlineCalendarEventAddReleaseStatus(builder, releaseStatus):
    builder.PrependUint8Slot(9, releaseStatus, 0)

def AddReleaseStatus(builder, releaseStatus):
    HeadlineCalendarEventAddReleaseStatus(builder, releaseStatus)

def HeadlineCalendarEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return HeadlineCalendarEventEnd(builder)
