# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

class Message(object):
    NONE = 0
    HeadlineEconomicEvent = 1
    HeadlineCalendarEvent = 2
    MacroReferenceData = 3
    MacroHeadlineEvent = 4
    MacroCalendarEvent = 5
    LogMessage = 6
