# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

class Message(object):
    NONE = 0
    HeadlineEconomicEvent = 1
    HeadlineCalendarEvent = 2
    LogMessage = 3
