# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

class ModuleType(object):
    ModuleUnknown = 0
    ModuleSystem = 1
    ModuleSession = 2
    ModuleSubscription = 3
    ModuleService = 4
    ModuleHearbeat = 5
    ModuleAnother = 99
