# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

class ServiceStatusType(object):
    ServiceUnknown = 0
    ServiceOpened = 1
    ServiceClosed = 2
    ServiceFailure = 3
    ServiceAnother = 99
