# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

class SessionType(object):
    Unknowk = 0
    SessionConnectionUp = 1
    SessionStarted = 2
    SessionConnectionDown = 3
    SessionTerminated = 4
    Another = 99
