# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

class SubscriptionStatusType(object):
    SubscriptionUnknown = 0
    SubscriptionStarted = 1
    SubscriptionStreamsActivated = 2
    SubscriptionTerminated = 3
    SubscriptionSuccess = 4
    SubscriptionFailure = 5
    SubscriptionAnother = 99
