// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FB

import "strconv"

type EventSubType int32

const (
	EventSubTypeUnknown   EventSubType = 0
	EventSubTypeNew       EventSubType = 1
	EventSubTypeUpdate    EventSubType = 2
	EventSubTypeUnitpaint EventSubType = 3
	EventSubTypeDelete    EventSubType = 4
	EventSubTypeAnother   EventSubType = 99
)

var EnumNamesEventSubType = map[EventSubType]string{
	EventSubTypeUnknown:   "Unknown",
	EventSubTypeNew:       "New",
	EventSubTypeUpdate:    "Update",
	EventSubTypeUnitpaint: "Unitpaint",
	EventSubTypeDelete:    "Delete",
	EventSubTypeAnother:   "Another",
}

var EnumValuesEventSubType = map[string]EventSubType{
	"Unknown":   EventSubTypeUnknown,
	"New":       EventSubTypeNew,
	"Update":    EventSubTypeUpdate,
	"Unitpaint": EventSubTypeUnitpaint,
	"Delete":    EventSubTypeDelete,
	"Another":   EventSubTypeAnother,
}

func (v EventSubType) String() string {
	if s, ok := EnumNamesEventSubType[v]; ok {
		return s
	}
	return "EventSubType(" + strconv.FormatInt(int64(v), 10) + ")"
}
