// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FB

import "strconv"

type EventType int32

const (
	EventTypeUnknown  EventType = 0
	EventTypeActual   EventType = 1
	EventTypeRevision EventType = 2
	EventTypeEstimate EventType = 3
	EventTypeCalendar EventType = 4
	EventTypeAnother  EventType = 99
)

var EnumNamesEventType = map[EventType]string{
	EventTypeUnknown:  "Unknown",
	EventTypeActual:   "Actual",
	EventTypeRevision: "Revision",
	EventTypeEstimate: "Estimate",
	EventTypeCalendar: "Calendar",
	EventTypeAnother:  "Another",
}

var EnumValuesEventType = map[string]EventType{
	"Unknown":  EventTypeUnknown,
	"Actual":   EventTypeActual,
	"Revision": EventTypeRevision,
	"Estimate": EventTypeEstimate,
	"Calendar": EventTypeCalendar,
	"Another":  EventTypeAnother,
}

func (v EventType) String() string {
	if s, ok := EnumNamesEventType[v]; ok {
		return s
	}
	return "EventType(" + strconv.FormatInt(int64(v), 10) + ")"
}
