// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FB

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Main struct {
	_tab flatbuffers.Table
}

func GetRootAsMain(buf []byte, offset flatbuffers.UOffsetT) *Main {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Main{}
	x.Init(buf, n+offset)
	return x
}

func FinishMainBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMain(buf []byte, offset flatbuffers.UOffsetT) *Main {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Main{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMainBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Main) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Main) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Main) MessageType() Message {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Message(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Main) MutateMessageType(n Message) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *Main) Message(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func MainStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MainAddMessageType(builder *flatbuffers.Builder, messageType Message) {
	builder.PrependByteSlot(0, byte(messageType), 0)
}
func MainAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(message), 0)
}
func MainEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
