// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FB

import "strconv"

type Message byte

const (
	MessageNONE                  Message = 0
	MessageHeadlineEconomicEvent Message = 1
	MessageHeadlineCalendarEvent Message = 2
	MessageLogMessage            Message = 3
)

var EnumNamesMessage = map[Message]string{
	MessageNONE:                  "NONE",
	MessageHeadlineEconomicEvent: "HeadlineEconomicEvent",
	MessageHeadlineCalendarEvent: "HeadlineCalendarEvent",
	MessageLogMessage:            "LogMessage",
}

var EnumValuesMessage = map[string]Message{
	"NONE":                  MessageNONE,
	"HeadlineEconomicEvent": MessageHeadlineEconomicEvent,
	"HeadlineCalendarEvent": MessageHeadlineCalendarEvent,
	"LogMessage":            MessageLogMessage,
}

func (v Message) String() string {
	if s, ok := EnumNamesMessage[v]; ok {
		return s
	}
	return "Message(" + strconv.FormatInt(int64(v), 10) + ")"
}
