// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FB

import "strconv"

type Message byte

const (
	MessageNONE                  Message = 0
	MessageHeadlineEconomicEvent Message = 1
	MessageHeadlineCalendarEvent Message = 2
	MessageMacroReferenceData    Message = 3
	MessageMacroHeadlineEvent    Message = 4
	MessageMacroCalendarEvent    Message = 5
	MessageLogMessage            Message = 6
)

var EnumNamesMessage = map[Message]string{
	MessageNONE:                  "NONE",
	MessageHeadlineEconomicEvent: "HeadlineEconomicEvent",
	MessageHeadlineCalendarEvent: "HeadlineCalendarEvent",
	MessageMacroReferenceData:    "MacroReferenceData",
	MessageMacroHeadlineEvent:    "MacroHeadlineEvent",
	MessageMacroCalendarEvent:    "MacroCalendarEvent",
	MessageLogMessage:            "LogMessage",
}

var EnumValuesMessage = map[string]Message{
	"NONE":                  MessageNONE,
	"HeadlineEconomicEvent": MessageHeadlineEconomicEvent,
	"HeadlineCalendarEvent": MessageHeadlineCalendarEvent,
	"MacroReferenceData":    MessageMacroReferenceData,
	"MacroHeadlineEvent":    MessageMacroHeadlineEvent,
	"MacroCalendarEvent":    MessageMacroCalendarEvent,
	"LogMessage":            MessageLogMessage,
}

func (v Message) String() string {
	if s, ok := EnumNamesMessage[v]; ok {
		return s
	}
	return "Message(" + strconv.FormatInt(int64(v), 10) + ")"
}
