// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FB

import "strconv"

type ModuleType byte

const (
	ModuleTypeModuleUnknown      ModuleType = 0
	ModuleTypeModuleSystem       ModuleType = 1
	ModuleTypeModuleSession      ModuleType = 2
	ModuleTypeModuleSubscription ModuleType = 3
	ModuleTypeModuleService      ModuleType = 4
	ModuleTypeModuleHearbeat     ModuleType = 5
	ModuleTypeModuleAnother      ModuleType = 99
)

var EnumNamesModuleType = map[ModuleType]string{
	ModuleTypeModuleUnknown:      "ModuleUnknown",
	ModuleTypeModuleSystem:       "ModuleSystem",
	ModuleTypeModuleSession:      "ModuleSession",
	ModuleTypeModuleSubscription: "ModuleSubscription",
	ModuleTypeModuleService:      "ModuleService",
	ModuleTypeModuleHearbeat:     "ModuleHearbeat",
	ModuleTypeModuleAnother:      "ModuleAnother",
}

var EnumValuesModuleType = map[string]ModuleType{
	"ModuleUnknown":      ModuleTypeModuleUnknown,
	"ModuleSystem":       ModuleTypeModuleSystem,
	"ModuleSession":      ModuleTypeModuleSession,
	"ModuleSubscription": ModuleTypeModuleSubscription,
	"ModuleService":      ModuleTypeModuleService,
	"ModuleHearbeat":     ModuleTypeModuleHearbeat,
	"ModuleAnother":      ModuleTypeModuleAnother,
}

func (v ModuleType) String() string {
	if s, ok := EnumNamesModuleType[v]; ok {
		return s
	}
	return "ModuleType(" + strconv.FormatInt(int64(v), 10) + ")"
}
