// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FB

import "strconv"

type ReleaseStatus int32

const (
	ReleaseStatusUnknown   ReleaseStatus = 0
	ReleaseStatusReleased  ReleaseStatus = 1
	ReleaseStatusScheduled ReleaseStatus = 2
	ReleaseStatusAnother   ReleaseStatus = 99
)

var EnumNamesReleaseStatus = map[ReleaseStatus]string{
	ReleaseStatusUnknown:   "Unknown",
	ReleaseStatusReleased:  "Released",
	ReleaseStatusScheduled: "Scheduled",
	ReleaseStatusAnother:   "Another",
}

var EnumValuesReleaseStatus = map[string]ReleaseStatus{
	"Unknown":   ReleaseStatusUnknown,
	"Released":  ReleaseStatusReleased,
	"Scheduled": ReleaseStatusScheduled,
	"Another":   ReleaseStatusAnother,
}

func (v ReleaseStatus) String() string {
	if s, ok := EnumNamesReleaseStatus[v]; ok {
		return s
	}
	return "ReleaseStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
