// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FB

import "strconv"

type ServiceStatusType byte

const (
	ServiceStatusTypeServiceUnknown ServiceStatusType = 0
	ServiceStatusTypeServiceOpened  ServiceStatusType = 1
	ServiceStatusTypeServiceClosed  ServiceStatusType = 2
	ServiceStatusTypeServiceFailure ServiceStatusType = 3
	ServiceStatusTypeServiceAnother ServiceStatusType = 99
)

var EnumNamesServiceStatusType = map[ServiceStatusType]string{
	ServiceStatusTypeServiceUnknown: "ServiceUnknown",
	ServiceStatusTypeServiceOpened:  "ServiceOpened",
	ServiceStatusTypeServiceClosed:  "ServiceClosed",
	ServiceStatusTypeServiceFailure: "ServiceFailure",
	ServiceStatusTypeServiceAnother: "ServiceAnother",
}

var EnumValuesServiceStatusType = map[string]ServiceStatusType{
	"ServiceUnknown": ServiceStatusTypeServiceUnknown,
	"ServiceOpened":  ServiceStatusTypeServiceOpened,
	"ServiceClosed":  ServiceStatusTypeServiceClosed,
	"ServiceFailure": ServiceStatusTypeServiceFailure,
	"ServiceAnother": ServiceStatusTypeServiceAnother,
}

func (v ServiceStatusType) String() string {
	if s, ok := EnumNamesServiceStatusType[v]; ok {
		return s
	}
	return "ServiceStatusType(" + strconv.FormatInt(int64(v), 10) + ")"
}
