// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FB

import "strconv"

type SessionStatusType int32

const (
	SessionStatusTypeSessionUnknown        SessionStatusType = 0
	SessionStatusTypeSessionConnectionUp   SessionStatusType = 1
	SessionStatusTypeSessionStarted        SessionStatusType = 2
	SessionStatusTypeSessionConnectionDown SessionStatusType = 3
	SessionStatusTypeSessionTerminated     SessionStatusType = 4
	SessionStatusTypeSessionAnother        SessionStatusType = 99
)

var EnumNamesSessionStatusType = map[SessionStatusType]string{
	SessionStatusTypeSessionUnknown:        "SessionUnknown",
	SessionStatusTypeSessionConnectionUp:   "SessionConnectionUp",
	SessionStatusTypeSessionStarted:        "SessionStarted",
	SessionStatusTypeSessionConnectionDown: "SessionConnectionDown",
	SessionStatusTypeSessionTerminated:     "SessionTerminated",
	SessionStatusTypeSessionAnother:        "SessionAnother",
}

var EnumValuesSessionStatusType = map[string]SessionStatusType{
	"SessionUnknown":        SessionStatusTypeSessionUnknown,
	"SessionConnectionUp":   SessionStatusTypeSessionConnectionUp,
	"SessionStarted":        SessionStatusTypeSessionStarted,
	"SessionConnectionDown": SessionStatusTypeSessionConnectionDown,
	"SessionTerminated":     SessionStatusTypeSessionTerminated,
	"SessionAnother":        SessionStatusTypeSessionAnother,
}

func (v SessionStatusType) String() string {
	if s, ok := EnumNamesSessionStatusType[v]; ok {
		return s
	}
	return "SessionStatusType(" + strconv.FormatInt(int64(v), 10) + ")"
}
