// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FB

import "strconv"

type SessionType int32

const (
	SessionTypeUnknowk               SessionType = 0
	SessionTypeSessionConnectionUp   SessionType = 1
	SessionTypeSessionStarted        SessionType = 2
	SessionTypeSessionConnectionDown SessionType = 3
	SessionTypeSessionTerminated     SessionType = 4
	SessionTypeAnother               SessionType = 99
)

var EnumNamesSessionType = map[SessionType]string{
	SessionTypeUnknowk:               "Unknowk",
	SessionTypeSessionConnectionUp:   "SessionConnectionUp",
	SessionTypeSessionStarted:        "SessionStarted",
	SessionTypeSessionConnectionDown: "SessionConnectionDown",
	SessionTypeSessionTerminated:     "SessionTerminated",
	SessionTypeAnother:               "Another",
}

var EnumValuesSessionType = map[string]SessionType{
	"Unknowk":               SessionTypeUnknowk,
	"SessionConnectionUp":   SessionTypeSessionConnectionUp,
	"SessionStarted":        SessionTypeSessionStarted,
	"SessionConnectionDown": SessionTypeSessionConnectionDown,
	"SessionTerminated":     SessionTypeSessionTerminated,
	"Another":               SessionTypeAnother,
}

func (v SessionType) String() string {
	if s, ok := EnumNamesSessionType[v]; ok {
		return s
	}
	return "SessionType(" + strconv.FormatInt(int64(v), 10) + ")"
}
