// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FB

import "strconv"

type SubscriptionStatusType byte

const (
	SubscriptionStatusTypeSubscriptionUnknown          SubscriptionStatusType = 0
	SubscriptionStatusTypeSubscriptionStarted          SubscriptionStatusType = 1
	SubscriptionStatusTypeSubscriptionStreamsActivated SubscriptionStatusType = 2
	SubscriptionStatusTypeSubscriptionTerminated       SubscriptionStatusType = 3
	SubscriptionStatusTypeSubscriptionSuccess          SubscriptionStatusType = 4
	SubscriptionStatusTypeSubscriptionFailure          SubscriptionStatusType = 5
	SubscriptionStatusTypeSubscriptionAnother          SubscriptionStatusType = 99
)

var EnumNamesSubscriptionStatusType = map[SubscriptionStatusType]string{
	SubscriptionStatusTypeSubscriptionUnknown:          "SubscriptionUnknown",
	SubscriptionStatusTypeSubscriptionStarted:          "SubscriptionStarted",
	SubscriptionStatusTypeSubscriptionStreamsActivated: "SubscriptionStreamsActivated",
	SubscriptionStatusTypeSubscriptionTerminated:       "SubscriptionTerminated",
	SubscriptionStatusTypeSubscriptionSuccess:          "SubscriptionSuccess",
	SubscriptionStatusTypeSubscriptionFailure:          "SubscriptionFailure",
	SubscriptionStatusTypeSubscriptionAnother:          "SubscriptionAnother",
}

var EnumValuesSubscriptionStatusType = map[string]SubscriptionStatusType{
	"SubscriptionUnknown":          SubscriptionStatusTypeSubscriptionUnknown,
	"SubscriptionStarted":          SubscriptionStatusTypeSubscriptionStarted,
	"SubscriptionStreamsActivated": SubscriptionStatusTypeSubscriptionStreamsActivated,
	"SubscriptionTerminated":       SubscriptionStatusTypeSubscriptionTerminated,
	"SubscriptionSuccess":          SubscriptionStatusTypeSubscriptionSuccess,
	"SubscriptionFailure":          SubscriptionStatusTypeSubscriptionFailure,
	"SubscriptionAnother":          SubscriptionStatusTypeSubscriptionAnother,
}

func (v SubscriptionStatusType) String() string {
	if s, ok := EnumNamesSubscriptionStatusType[v]; ok {
		return s
	}
	return "SubscriptionStatusType(" + strconv.FormatInt(int64(v), 10) + ")"
}
