// Code generated by "stringer -type=EventSubType"; DO NOT EDIT.

package blpconngo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventSubTypeUnknown-0]
	_ = x[EventSubTypeNew-1]
	_ = x[EventSubTypeUpdate-2]
	_ = x[EventSubTypeUnitpaint-3]
	_ = x[EventSubTypeDelete-4]
}

const _EventSubType_name = "EventSubTypeUnknownEventSubTypeNewEventSubTypeUpdateEventSubTypeUnitpaintEventSubTypeDelete"

var _EventSubType_index = [...]uint8{0, 19, 34, 52, 73, 91}

func (i EventSubType) String() string {
	if i >= EventSubType(len(_EventSubType_index)-1) {
		return "EventSubType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventSubType_name[_EventSubType_index[i]:_EventSubType_index[i+1]]
}
