// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package blpconngo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventTypeUnknown-0]
	_ = x[EventTypeActual-1]
	_ = x[EventTypeRevision-2]
	_ = x[EventTypeEstimate-3]
	_ = x[EventTypeCalendar-4]
}

const _EventType_name = "EventTypeUnknownEventTypeActualEventTypeRevisionEventTypeEstimateEventTypeCalendar"

var _EventType_index = [...]uint8{0, 16, 31, 48, 65, 82}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
