// Code generated by "stringer -type=ModuleType"; DO NOT EDIT.

package blpconngo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModuleUnknown-0]
	_ = x[ModuleSystem-1]
	_ = x[ModuleSession-2]
	_ = x[ModuleSubscription-3]
	_ = x[ModuleService-4]
	_ = x[ModuleHeartbeat-5]
}

const _ModuleType_name = "ModuleUnknownModuleSystemModuleSessionModuleSubscriptionModuleServiceModuleHeartbeat"

var _ModuleType_index = [...]uint8{0, 13, 25, 38, 56, 69, 84}

func (i ModuleType) String() string {
	if i >= ModuleType(len(_ModuleType_index)-1) {
		return "ModuleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ModuleType_name[_ModuleType_index[i]:_ModuleType_index[i+1]]
}
