// Code generated by "stringer -type=ReleaseStatus"; DO NOT EDIT.

package blpconngo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReleaseStatusUnknown-0]
	_ = x[ReleaseStatusReleased-1]
	_ = x[ReleaseStatusScheduled-2]
}

const _ReleaseStatus_name = "ReleaseStatusUnknownReleaseStatusReleasedReleaseStatusScheduled"

var _ReleaseStatus_index = [...]uint8{0, 20, 41, 63}

func (i ReleaseStatus) String() string {
	if i >= ReleaseStatus(len(_ReleaseStatus_index)-1) {
		return "ReleaseStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReleaseStatus_name[_ReleaseStatus_index[i]:_ReleaseStatus_index[i+1]]
}
