// Code generated by "stringer -type=ServiceStatus"; DO NOT EDIT.

package blpconngo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServiceUnknown-0]
	_ = x[ServiceOpened-1]
	_ = x[ServiceClosed-2]
	_ = x[ServiceFailure-3]
}

const _ServiceStatus_name = "ServiceUnknownServiceOpenedServiceClosedServiceFailure"

var _ServiceStatus_index = [...]uint8{0, 14, 27, 40, 54}

func (i ServiceStatus) String() string {
	if i >= ServiceStatus(len(_ServiceStatus_index)-1) {
		return "ServiceStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServiceStatus_name[_ServiceStatus_index[i]:_ServiceStatus_index[i+1]]
}
