// Code generated by "stringer -type=SessionStatus"; DO NOT EDIT.

package blpconngo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SessionUnknown-0]
	_ = x[SessionConnectionUp-1]
	_ = x[SessionStarted-2]
	_ = x[SessionConnectionDown-3]
	_ = x[SessionTerminated-4]
	_ = x[SessionInvalidOptions-5]
	_ = x[SessionFailure-6]
}

const _SessionStatus_name = "SessionUnknownSessionConnectionUpSessionStartedSessionConnectionDownSessionTerminatedSessionInvalidOptionsSessionFailure"

var _SessionStatus_index = [...]uint8{0, 14, 33, 47, 68, 85, 106, 120}

func (i SessionStatus) String() string {
	if i >= SessionStatus(len(_SessionStatus_index)-1) {
		return "SessionStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SessionStatus_name[_SessionStatus_index[i]:_SessionStatus_index[i+1]]
}
