// Code generated by "stringer -type=SubscriptionStatus"; DO NOT EDIT.

package blpconngo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SubscriptionUnknown-0]
	_ = x[SubscriptionStarted-1]
	_ = x[SubscriptionStreamsActivated-2]
	_ = x[SubscriptionTerminated-3]
	_ = x[SubscriptionSuccess-4]
	_ = x[SubscriptionFailure-5]
}

const _SubscriptionStatus_name = "SubscriptionUnknownSubscriptionStartedSubscriptionStreamsActivatedSubscriptionTerminatedSubscriptionSuccessSubscriptionFailure"

var _SubscriptionStatus_index = [...]uint8{0, 19, 38, 66, 88, 107, 126}

func (i SubscriptionStatus) String() string {
	if i >= SubscriptionStatus(len(_SubscriptionStatus_index)-1) {
		return "SubscriptionStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SubscriptionStatus_name[_SubscriptionStatus_index[i]:_SubscriptionStatus_index[i+1]]
}
