# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Message

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DateRange(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DateRange()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDateRange(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DateRange
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DateRange
    def Start(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from BlpConn.Message.DateTime import DateTime
            obj = DateTime()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DateRange
    def End(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from BlpConn.Message.DateTime import DateTime
            obj = DateTime()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def DateRangeStart(builder):
    builder.StartObject(2)

def Start(builder):
    DateRangeStart(builder)

def DateRangeAddStart(builder, start):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(start), 0)

def AddStart(builder, start):
    DateRangeAddStart(builder, start)

def DateRangeAddEnd(builder, end):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(end), 0)

def AddEnd(builder, end):
    DateRangeAddEnd(builder, end)

def DateRangeEnd(builder):
    return builder.EndObject()

def End(builder):
    return DateRangeEnd(builder)
