# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Message

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DateTime(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DateTime()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDateTime(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DateTime
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DateTime
    def Micros(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # DateTime
    def Offset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

def DateTimeStart(builder):
    builder.StartObject(2)

def Start(builder):
    DateTimeStart(builder)

def DateTimeAddMicros(builder, micros):
    builder.PrependUint64Slot(0, micros, 0)

def AddMicros(builder, micros):
    DateTimeAddMicros(builder, micros)

def DateTimeAddOffset(builder, offset):
    builder.PrependInt16Slot(1, offset, 0)

def AddOffset(builder, offset):
    DateTimeAddOffset(builder, offset)

def DateTimeEnd(builder):
    return builder.EndObject()

def End(builder):
    return DateTimeEnd(builder)
