# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Message

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EmptyEconomicEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EmptyEconomicEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEmptyEconomicEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EmptyEconomicEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def EmptyEconomicEventStart(builder):
    builder.StartObject(0)

def Start(builder):
    EmptyEconomicEventStart(builder)

def EmptyEconomicEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return EmptyEconomicEventEnd(builder)
